### ISSUE TITLE
Missing linked files 

### ISSUE THREAD

**Issue by Asppagh** [QinqinHuang/CAS_eQTL#1]
I would like to run Response_eQTLs test in the following script in my analyses, but I see that it requires two other scripts that I can not find in the project.
https://github.com/QinqinHuang/CAS_eQTL/blob/master/Response_eQTLs/1_Interaction_test_topeSNPs_permutation.R
The script linked in the this test are mentioned in below:
source("/projects/qinqinhuang/CAS/Analysis/Scripts/score_rwald_LR_test_Agus.R")
source("/projects/qinqinhuang/CAS/Analysis/Scripts/CAS_My_Functions_load_data.R")

Could you please let me know where can I find these two files?

**Comment by QinqinHuang** [comment]
Hi Ahmad,

I've uploaded both scripts. Note that the script to load data only works when you have similar input data files after updating the file paths, but I uploaded it anyways in case it's helpful for understanding the data format. 

Cheers
